/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import business.AgeCheck;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import persistence.MoneyControl;
import persistence.MoneyControlDao;

/**
 *
 * @author Outro eu
 */
public class LoginTela extends javax.swing.JFrame {

    MoneyControlDao dao;
    MoneyControl user;

    Color LIGHT_GREEN = new Color(179, 208, 102);
    Color HARD_GREEN = new Color(68, 128, 64);
    Color GREEN_BLUE = new Color(19, 96, 80);
    Color MY_YELLOW = new Color(253, 235, 91);
    Color MY_RED = new Color(255, 89, 49);

    public static String email;
    public static String nome;
    public static int id;
    public static String senha;
    public static String sobrenome;
    public static String dataNasc;
    public static String cpf;

    /**
     * Creates new form LoginTela
     */
    public LoginTela() {
        initComponents();

        btnEsconder.setVisible(false);

        txtUsuarioInterno.requestFocus();

        txtUsuario.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, LIGHT_GREEN));
        txtSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, LIGHT_GREEN));
        txtUsuario.setBackground(GREEN_BLUE);
        txtUsuarioInterno.setBackground(GREEN_BLUE);
        txtSenha.setBackground(GREEN_BLUE);
        txtSenhaInterno.setBackground(GREEN_BLUE);

        getContentPane().setBackground(GREEN_BLUE);

        setFalseCadastro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnEsconder = new javax.swing.JButton();
        txtUsuarioInterno = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenhaInterno = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblCadastro = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblMessagem = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblFazerSenha = new javax.swing.JLabel();
        txtFazerSenha = new javax.swing.JTextField();
        lblBg = new javax.swing.JLabel();
        lblPrimeiroNome = new javax.swing.JLabel();
        txtPrimeiroNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblBg2 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        lblRepetirSenha = new javax.swing.JLabel();
        txtRepetirSenha = new javax.swing.JTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        btnFazerCadastro = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtSobrenome = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNITECH - CONTROLE DE GASTOS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuário(a):");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(620, 140, 80, 20);

        lblLogin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Faça o login :)");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(730, 40, 150, 30);

        btnMostrar.setBackground(new java.awt.Color(204, 255, 204));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (2) (1).png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(880, 180, 40, 30);

        btnEsconder.setBackground(new java.awt.Color(204, 255, 204));
        btnEsconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder);
        btnEsconder.setBounds(880, 180, 40, 30);

        txtUsuarioInterno.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuarioInterno.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioInterno.setBorder(null);
        txtUsuarioInterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioInternoKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuarioInterno);
        txtUsuarioInterno.setBounds(720, 130, 190, 30);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(620, 190, 80, 20);

        txtSenhaInterno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSenhaInterno.setForeground(new java.awt.Color(255, 255, 255));
        txtSenhaInterno.setBorder(null);
        txtSenhaInterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaInternoKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenhaInterno);
        txtSenhaInterno.setBounds(720, 180, 190, 30);

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUsuario.setAlignmentX(0.9F);
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(2, 6, 2, 10));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(710, 130, 210, 30);

        txtSenha.setEditable(false);
        txtSenha.setBackground(new java.awt.Color(204, 204, 204));
        txtSenha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSenha.setAlignmentX(0.9F);
        txtSenha.setBorder(null);
        txtSenha.setMargin(new java.awt.Insets(2, 6, 2, 10));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(710, 180, 210, 30);

        btnEntrar.setBackground(new java.awt.Color(179, 208, 102));
        btnEntrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(68, 128, 64));
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(760, 260, 90, 30);

        lblCadastro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastro.setText("Novo por aqui? Cadastre-se agora:");
        getContentPane().add(lblCadastro);
        lblCadastro.setBounds(690, 320, 230, 20);

        btnCadastro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(179, 208, 102));
        btnCadastro.setText("Cadastrar-se");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(740, 350, 130, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(690, 3, 0, 440);

        lbl3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("uma vida mais plena e com significado...");
        getContentPane().add(lbl3);
        lbl3.setBounds(60, 180, 490, 20);

        lbl2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("é o primeiro passo para");
        getContentPane().add(lbl2);
        lbl2.setBounds(60, 150, 300, 20);

        lbl1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Porque uma vida financeira saudável ");
        getContentPane().add(lbl1);
        lbl1.setBounds(60, 110, 450, 40);

        lblMessagem.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lblMessagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMessagem.setText("Você está a um passo de ter sua vida financeira transformada :)");
        getContentPane().add(lblMessagem);
        lblMessagem.setBounds(500, 0, 450, 30);

        lblDataNasc.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        lblDataNasc.setText("Data de Nascimento");
        getContentPane().add(lblDataNasc);
        lblDataNasc.setBounds(530, 180, 140, 20);

        lblCpf.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("CPF:");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(530, 220, 50, 20);

        lblFazerSenha.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblFazerSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblFazerSenha.setText("Senha:");
        getContentPane().add(lblFazerSenha);
        lblFazerSenha.setBounds(530, 260, 60, 20);

        txtFazerSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFazerSenhaActionPerformed(evt);
            }
        });
        txtFazerSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFazerSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtFazerSenha);
        txtFazerSenha.setBounds(640, 250, 120, 30);

        lblBg.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lblBg.setForeground(new java.awt.Color(255, 255, 255));
        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img2.png"))); // NOI18N
        getContentPane().add(lblBg);
        lblBg.setBounds(-40, 130, 610, 550);

        lblPrimeiroNome.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblPrimeiroNome.setForeground(new java.awt.Color(255, 255, 255));
        lblPrimeiroNome.setText("Nome:");
        getContentPane().add(lblPrimeiroNome);
        lblPrimeiroNome.setBounds(530, 60, 90, 20);

        txtPrimeiroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimeiroNomeActionPerformed(evt);
            }
        });
        txtPrimeiroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrimeiroNomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrimeiroNome);
        txtPrimeiroNome.setBounds(640, 50, 200, 30);

        lblEmail.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(530, 140, 70, 20);

        lblBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-a.png"))); // NOI18N
        getContentPane().add(lblBg2);
        lblBg2.setBounds(80, 50, 300, 310);

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataNascKeyPressed(evt);
            }
        });
        getContentPane().add(txtDataNasc);
        txtDataNasc.setBounds(670, 170, 90, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(580, 210, 100, 30);

        lblRepetirSenha.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblRepetirSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblRepetirSenha.setText("Repetir senha:");
        getContentPane().add(lblRepetirSenha);
        lblRepetirSenha.setBounds(530, 300, 100, 20);

        txtRepetirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepetirSenhaActionPerformed(evt);
            }
        });
        txtRepetirSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRepetirSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtRepetirSenha);
        txtRepetirSenha.setBounds(640, 290, 120, 30);

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(640, 130, 280, 30);

        btnFazerCadastro.setBackground(new java.awt.Color(179, 208, 102));
        btnFazerCadastro.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnFazerCadastro.setForeground(new java.awt.Color(68, 128, 64));
        btnFazerCadastro.setText("Cadastrar");
        btnFazerCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFazerCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFazerCadastro);
        btnFazerCadastro.setBounds(520, 350, 110, 30);

        btnVoltar.setBackground(new java.awt.Color(255, 89, 49));
        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(650, 350, 80, 30);

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });
        txtSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSobrenomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtSobrenome);
        txtSobrenome.setBounds(640, 90, 200, 30);

        lblSobrenome.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        lblSobrenome.setText("Sobrenome:");
        getContentPane().add(lblSobrenome);
        lblSobrenome.setBounds(530, 100, 80, 20);

        setSize(new java.awt.Dimension(991, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed


    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        dao = new MoneyControlDao();
        user = new MoneyControl();
        boolean result;
        boolean conectou;

        conectou = dao.conectar();

        if (txtUsuarioInterno.getText().equals("") || txtSenhaInterno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos.");
            txtUsuarioInterno.requestFocus();
            return;
        }

        if (conectou) {
            user = dao.consultar(txtUsuarioInterno.getText(), txtSenhaInterno.getText());
            if (user == null) {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorreto.");
                txtUsuarioInterno.requestFocus();
            } else {
                nome = user.getNome();
                sobrenome = user.getSobrenome();
                email = user.getEmail();
                dataNasc = user.getDataNasc();
                cpf = user.getCpf();
                
                id = user.getId();
                senha = user.getSenha();

                TelaUsuario t;
                t = new TelaUsuario();
                t.setVisible(true);
                this.dispose();
                txtUsuarioInterno.setText("");
                txtSenhaInterno.setText("");
                txtUsuarioInterno.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro na conexão");
            txtUsuarioInterno.requestFocus();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtUsuarioInternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioInternoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtSenhaInterno.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioInternoKeyPressed

    private void txtSenhaInternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaInternoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_txtSenhaInternoKeyPressed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        txtPrimeiroNome.requestFocus();

        setFalseLogin();

        setTrueCadastro();

        limparLogin();
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void txtFazerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFazerSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFazerSenhaActionPerformed

    private void txtPrimeiroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimeiroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeiroNomeActionPerformed

    private void txtRepetirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepetirSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepetirSenhaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setTrueLogin();

        setFalseCadastro();

        limparCadastro();
        limparLogin();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPrimeiroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimeiroNomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtSobrenome.requestFocus();
        }
    }//GEN-LAST:event_txtPrimeiroNomeKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtDataNasc.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtDataNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataNascKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtCpf.requestFocus();
        }
    }//GEN-LAST:event_txtDataNascKeyPressed

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtFazerSenha.requestFocus();
        }
    }//GEN-LAST:event_txtCpfKeyPressed

    private void txtFazerSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFazerSenhaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtRepetirSenha.requestFocus();
        }
    }//GEN-LAST:event_txtFazerSenhaKeyPressed

    private void txtRepetirSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepetirSenhaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnFazerCadastro.doClick();
        }
    }//GEN-LAST:event_txtRepetirSenhaKeyPressed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtSobrenomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSobrenomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtSobrenomeKeyPressed

    private void btnFazerCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerCadastroActionPerformed
        boolean resposta;
        int result;
        MoneyControlDao dao;
        dao = new MoneyControlDao();
        AgeCheck age;
        age = new AgeCheck();
        int curAge;

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            java.sql.Date data = new java.sql.Date(format.parse(txtDataNasc.getText()).getTime());
            curAge = AgeCheck.calculaIdade(data);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        
        if (curAge >= 0 && curAge < 18) {
            JOptionPane.showMessageDialog(null, "Apenas maiores de idade podem criar uma conta.");
            txtDataNasc.requestFocus();
            return;
        } else if (curAge > 110 || curAge < 0) {
            JOptionPane.showMessageDialog(null, "Data inválida.");
            txtDataNasc.requestFocus();
            return;
        }
        
        if (txtPrimeiroNome.getText().equals("") || txtSobrenome.getText().equals("") || txtEmail.getText().equals("") || txtDataNasc.getText().equals("") || txtCpf.getText().equals("") || txtFazerSenha.getText().equals("") || txtRepetirSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            txtPrimeiroNome.requestFocus();
            return;
        }

        MoneyControl user;
        if (txtFazerSenha.getText().equals(txtRepetirSenha.getText())) {
            user = new MoneyControl(
                    txtPrimeiroNome.getText(),
                    txtSobrenome.getText(),
                    txtEmail.getText(),
                    txtDataNasc.getText(),
                    txtCpf.getText(),
                    txtFazerSenha.getText()
            );

            resposta = dao.conectar();
            if (resposta) {
                result = dao.cadastrar(user);
                if (result == 1062) {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado.");
                    txtPrimeiroNome.requestFocus();
                } else if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso. \nUse o email registrado para realizar o login.");
                    limparCadastro();
                    setFalseCadastro();
                    setTrueLogin();
                    txtUsuarioInterno.requestFocus();
                } else if (result == 0) {
                    JOptionPane.showMessageDialog(null, "Erro na conexão.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senhas incompatíveis");
            txtFazerSenha.requestFocus();
        }
    }//GEN-LAST:event_btnFazerCadastroActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        txtSenhaInterno.setEchoChar('\u0000');
        btnMostrar.setVisible(false);
        btnEsconder.setVisible(true);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEsconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderActionPerformed
        txtSenhaInterno.setEchoChar('*');
        btnMostrar.setVisible(true);
        btnEsconder.setVisible(false);
    }//GEN-LAST:event_btnEsconderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

    private void limparCadastro() {
        txtPrimeiroNome.setText("");
        txtSobrenome.setText("");
        txtEmail.setText("");
        txtDataNasc.setText("");
        txtCpf.setText("");
        txtFazerSenha.setText("");
        txtRepetirSenha.setText("");
    }

    private void limparLogin() {
        txtUsuarioInterno.setText("");
        txtSenhaInterno.setText("");
    }

    private void setFalseLogin() {
        lblLogin.setVisible(false);
        lblUsuario.setVisible(false);
        lblSenha.setVisible(false);
        lblCadastro.setVisible(false);
        lblBg.setVisible(false);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        txtUsuario.setVisible(false);
        txtUsuarioInterno.setVisible(false);
        txtSenha.setVisible(false);
        txtSenhaInterno.setVisible(false);
        btnEntrar.setVisible(false);
        btnCadastro.setVisible(false);
        btnMostrar.setVisible(false);
        btnEsconder.setVisible(false);
    }

    private void setTrueLogin() {
        lblLogin.setVisible(true);
        lblUsuario.setVisible(true);
        lblSenha.setVisible(true);
        lblCadastro.setVisible(true);
        lblBg.setVisible(true);
        lbl1.setVisible(true);
        lbl2.setVisible(true);
        lbl3.setVisible(true);
        txtUsuario.setVisible(true);
        txtUsuarioInterno.setVisible(true);
        txtSenha.setVisible(true);
        txtSenhaInterno.setVisible(true);
        btnEntrar.setVisible(true);
        btnCadastro.setVisible(true);
        btnMostrar.setVisible(true);
        btnEsconder.setVisible(true);
    }

    private void setTrueCadastro() {
        lblMessagem.setVisible(true);
        lblPrimeiroNome.setVisible(true);
        lblSobrenome.setVisible(true);
        lblEmail.setVisible(true);
        lblDataNasc.setVisible(true);
        lblCpf.setVisible(true);
        lblFazerSenha.setVisible(true);
        lblRepetirSenha.setVisible(true);
        lblBg2.setVisible(true);
        txtPrimeiroNome.setVisible(true);
        txtSobrenome.setVisible(true);
        txtEmail.setVisible(true);
        txtDataNasc.setVisible(true);
        txtCpf.setVisible(true);
        txtFazerSenha.setVisible(true);
        txtRepetirSenha.setVisible(true);
        btnFazerCadastro.setVisible(true);
        btnVoltar.setVisible(true);
    }

    private void setFalseCadastro() {
        lblMessagem.setVisible(false);
        lblPrimeiroNome.setVisible(false);
        lblSobrenome.setVisible(false);
        lblEmail.setVisible(false);
        lblDataNasc.setVisible(false);
        lblCpf.setVisible(false);
        lblFazerSenha.setVisible(false);
        lblRepetirSenha.setVisible(false);
        lblBg2.setVisible(false);
        txtPrimeiroNome.setVisible(false);
        txtSobrenome.setVisible(false);
        txtEmail.setVisible(false);
        txtDataNasc.setVisible(false);
        txtCpf.setVisible(false);
        txtFazerSenha.setVisible(false);
        txtRepetirSenha.setVisible(false);
        btnFazerCadastro.setVisible(false);
        btnVoltar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEsconder;
    private javax.swing.JButton btnFazerCadastro;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblBg2;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFazerSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMessagem;
    private javax.swing.JLabel lblPrimeiroNome;
    private javax.swing.JLabel lblRepetirSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JTextField txtFazerSenha;
    private javax.swing.JTextField txtPrimeiroNome;
    private javax.swing.JTextField txtRepetirSenha;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JPasswordField txtSenhaInterno;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioInterno;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the email
     */
    public String getEmail2() {
        return email;
    }

    /**
     * @return the nome
     */
    public String getNome2() {
        return nome;
    }
}
