/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import business.AgeCheck;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import persistence.MoneyControl;
import persistence.MoneyControlDao;
import static view.LoginTela.cpf;
import static view.LoginTela.dataNasc;
import static view.LoginTela.email;
import static view.LoginTela.id;
import static view.LoginTela.nome;
import static view.LoginTela.senha;
import static view.LoginTela.sobrenome;

/**
 *
 * @author Luccas Torres
 */
public class TelaAlterarDados extends javax.swing.JFrame {

    Color LIGHT_GREEN = new Color(179, 208, 102);
    Color HARD_GREEN = new Color(68, 128, 64);
    Color GREEN_BLUE = new Color(19, 96, 80);
    Color MY_YELLOW = new Color(253, 235, 91);
    Color MY_RED = new Color(255, 89, 49);

    MoneyControl dadosUser;
    MoneyControlDao dao;

    public TelaAlterarDados() {
        initComponents();
        hideExcluirConta();

        
        
        txtNome.setText(nome);
        txtSobrenome.setText(sobrenome);
        txtDataNasc.setText(dataNasc);
        txtEmail.setText(email);
        txtCpf.setText(cpf);
        getContentPane().setBackground(GREEN_BLUE);

        btnAlterar.setBackground(LIGHT_GREEN);
        btnCancelar.setBackground(MY_RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDigitarSenha = new javax.swing.JLabel();
        btnContaExcluir = new javax.swing.JButton();
        pswExcluirConta = new javax.swing.JPasswordField();
        btnCancelarExcluir = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEsconder4 = new javax.swing.JButton();
        lblBoxExcluir = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JFormattedTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEsconder = new javax.swing.JButton();
        btnEsconder1 = new javax.swing.JButton();
        btnEsconder2 = new javax.swing.JButton();
        btnEsconder3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();

        setTitle("ALTERAR DADOS DE CADASTRO");
        getContentPane().setLayout(null);

        lblDigitarSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDigitarSenha.setText("Digite sua senha:");
        getContentPane().add(lblDigitarSenha);
        lblDigitarSenha.setBounds(170, 20, 130, 50);

        btnContaExcluir.setBackground(new java.awt.Color(179, 208, 102));
        btnContaExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnContaExcluir.setText("Confirmar ");
        btnContaExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnContaExcluir);
        btnContaExcluir.setBounds(220, 180, 140, 30);

        pswExcluirConta.setBackground(new java.awt.Color(204, 204, 204));
        pswExcluirConta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pswExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswExcluirContaActionPerformed(evt);
            }
        });
        pswExcluirConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswExcluirContaKeyPressed(evt);
            }
        });
        getContentPane().add(pswExcluirConta);
        pswExcluirConta.setBounds(150, 90, 160, 30);

        btnCancelarExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelarExcluir.setText("Cancelar");
        btnCancelarExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarExcluir);
        btnCancelarExcluir.setBounds(100, 180, 100, 30);

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (2) (1).png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(310, 90, 30, 30);

        btnEsconder4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder4.setBorder(null);
        btnEsconder4.setContentAreaFilled(false);
        btnEsconder4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconder4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder4);
        btnEsconder4.setBounds(310, 90, 30, 30);

        lblBoxExcluir.setBackground(new java.awt.Color(255, 255, 255));
        lblBoxExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBoxExcluir.setOpaque(true);
        getContentPane().add(lblBoxExcluir);
        lblBoxExcluir.setBounds(60, 0, 330, 250);

        btnAlterar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(68, 128, 64));
        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(30, 260, 90, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data de Nascimento:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 140, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sobrenome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 90, 20);

        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(150, 260, 120, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 40, 50, 20);

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataNascKeyPressed(evt);
            }
        });
        getContentPane().add(txtDataNasc);
        txtDataNasc.setBounds(180, 110, 90, 30);

        txtSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSobrenomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtSobrenome);
        txtSobrenome.setBounds(130, 70, 170, 30);

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(130, 150, 170, 30);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(130, 30, 170, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 50, 20);

        btnEsconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder.setBorder(null);
        btnEsconder.setContentAreaFilled(false);
        btnEsconder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder);
        btnEsconder.setBounds(490, 90, 30, 30);

        btnEsconder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder1.setBorder(null);
        btnEsconder1.setContentAreaFilled(false);
        btnEsconder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconder1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder1);
        btnEsconder1.setBounds(490, 90, 30, 30);

        btnEsconder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder2.setBorder(null);
        btnEsconder2.setContentAreaFilled(false);
        btnEsconder2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconder2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder2);
        btnEsconder2.setBounds(490, 90, 30, 30);

        btnEsconder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder3.setBorder(null);
        btnEsconder3.setContentAreaFilled(false);
        btnEsconder3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconder3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder3);
        btnEsconder3.setBounds(500, 120, 30, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 50, 20);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(120, 190, 160, 30);

        setSize(new java.awt.Dimension(450, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AgeCheck age;
        age = new AgeCheck();
        int curAge;

        
        if (txtNome.getText().equals("") || txtSobrenome.getText().equals("") || txtDataNasc.getText().equals("") || txtEmail.getText().equals("") || txtCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            return;
        }
        
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            java.sql.Date data = new java.sql.Date(format.parse(txtDataNasc.getText()).getTime());
            curAge = AgeCheck.calculaIdade(data);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }

        if (curAge >= 0 && curAge < 18 ) {
            JOptionPane.showMessageDialog(null, "Apenas maiores de idade podem criar uma conta.");
            txtDataNasc.requestFocus();
            return;
        } else if (curAge > 110 || curAge < 0) {
            JOptionPane.showMessageDialog(null, "Data inválida.");
            txtDataNasc.requestFocus();
            return;
        } 
        showExcluirConta();
        naoClicavel();
        btnEsconder4.setVisible(false);
        pswExcluirConta.requestFocus();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TelaUsuario t = new TelaUsuario();
        t.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDataNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataNascKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtDataNascKeyPressed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtSobrenome.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtSobrenomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSobrenomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtDataNasc.requestFocus();
        }
    }//GEN-LAST:event_txtSobrenomeKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtCpf.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void btnContaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaExcluirActionPerformed
        MoneyControlDao dao;
        dao = new MoneyControlDao();
        boolean excluiu;
        boolean conectou;
        int result;
        
        conectou = dao.conectar();

        if (!pswExcluirConta.getText().equals(senha)) {
            JOptionPane.showMessageDialog(null, "Senha incorreta");
            pswExcluirConta.requestFocus();
            return;
        }

        MoneyControl user;
        user = new MoneyControl(
                txtNome.getText(),
                txtSobrenome.getText(),
                txtEmail.getText(),
                txtDataNasc.getText(),
                txtCpf.getText()
        );
        conectou = dao.conectar();

        

        if (conectou) {
                result = dao.alterar(user, id);

                if (result == 1) {

                    pswExcluirConta.requestFocus();
                    JOptionPane.showMessageDialog(null, "Alteração salva.");
                    hideExcluirConta();
                    clicavel();
                    pswExcluirConta.setText("");
                    nome = txtNome.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Email já cadastrado.");
                    txtEmail.requestFocus();
                }
            
        } else {
            JOptionPane.showMessageDialog(null, "Erro conexão.");
        }
    }//GEN-LAST:event_btnContaExcluirActionPerformed

    private void btnCancelarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarExcluirActionPerformed
        pswExcluirConta.setText("");
        hideExcluirConta();
        clicavel();
    }//GEN-LAST:event_btnCancelarExcluirActionPerformed

    private void pswExcluirContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswExcluirContaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnContaExcluir.doClick();
        }
    }//GEN-LAST:event_pswExcluirContaKeyPressed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        pswExcluirConta.setEchoChar('\u0000');
        btnMostrar.setVisible(false);
        btnEsconder4.setVisible(true);
        pswExcluirConta.requestFocus();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEsconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderActionPerformed
        pswExcluirConta.setEchoChar('*');
        
        pswExcluirConta.requestFocus();
        btnEsconder4.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconderActionPerformed

    private void btnEsconder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconder1ActionPerformed
        pswExcluirConta.setEchoChar('*');
        btnEsconder4.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconder1ActionPerformed

    private void btnEsconder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconder2ActionPerformed
        pswExcluirConta.setEchoChar('*');
        btnEsconder4.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconder2ActionPerformed

    private void btnEsconder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconder3ActionPerformed
        pswExcluirConta.setEchoChar('*');
        btnEsconder4.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconder3ActionPerformed

    private void btnEsconder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconder4ActionPerformed
        pswExcluirConta.setEchoChar('*');
        btnEsconder4.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconder4ActionPerformed

    private void pswExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswExcluirContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswExcluirContaActionPerformed

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnAlterar.doClick();
        }
    }//GEN-LAST:event_txtCpfKeyPressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarDados().setVisible(true);
            }
        });
    }

    private void naoClicavel() {
        btnAlterar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    private void clicavel() {
        btnAlterar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }

    private void hideExcluirConta() {
        lblBoxExcluir.setVisible(false);
        lblDigitarSenha.setVisible(false);
        pswExcluirConta.setVisible(false);
        btnCancelarExcluir.setVisible(false);
        btnContaExcluir.setVisible(false);
        btnMostrar.setVisible(false);
        btnEsconder4.setVisible(false);
    }

    private void showExcluirConta() {
        lblBoxExcluir.setVisible(true);
        lblDigitarSenha.setVisible(true);
        pswExcluirConta.setVisible(true);
        btnCancelarExcluir.setVisible(true);
        btnContaExcluir.setVisible(true);
        btnMostrar.setVisible(true);
        btnEsconder4.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarExcluir;
    private javax.swing.JButton btnContaExcluir;
    private javax.swing.JButton btnEsconder;
    private javax.swing.JButton btnEsconder1;
    private javax.swing.JButton btnEsconder2;
    private javax.swing.JButton btnEsconder3;
    private javax.swing.JButton btnEsconder4;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBoxExcluir;
    private javax.swing.JLabel lblDigitarSenha;
    private javax.swing.JPasswordField pswExcluirConta;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
