/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import persistence.MoneyControl;
import persistence.MoneyControlDao;
import static view.LoginTela.id;
import static view.LoginTela.nome;
import static view.LoginTela.senha;

/**
 *
 * @author Outro eu
 */
public class TelaUsuario extends javax.swing.JFrame {

    Color LIGHT_GREEN = new Color(179, 208, 102);
    Color HARD_GREEN = new Color(68, 128, 64);
    Color GREEN_BLUE = new Color(19, 96, 80);
    Color MY_YELLOW = new Color(253, 235, 91);
    Color MY_RED = new Color(255, 89, 49);

    //MoneyControlDao dao = new MoneyControlDao();
    //double saldo = dao.saldo(id);
    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();

        hideMenu();
        hideExcluirConta();
        btnFecharMenu.setVisible(false);

        txtSaldo.setText(" R$ " + saldoAqui(id));

        lblWelcome.setText("Boas vindas, " + nome + "!");

        jMenuBar1.setVisible(false);
        btnFecharMenu.setVisible(false);
        lblMenu.setBackground(GREEN_BLUE);
        lblMenu.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, GREEN_BLUE));
        txtValorEntrada.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, MY_YELLOW));
        txtValorEntrada.setBackground(HARD_GREEN);
        txtValorSaida.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, MY_YELLOW));
        txtValorSaida.setBackground(MY_RED);

        txtDataEntrada.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, MY_YELLOW));
        txtDataEntrada.setBackground(HARD_GREEN);
        txtDataSaida.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, MY_YELLOW));
        txtDataSaida.setBackground(MY_RED);

        btnSair.setBackground(LIGHT_GREEN);

        getContentPane().setBackground(MY_YELLOW);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblBarraMenu = new javax.swing.JLabel();
        btnAlterarDados = new javax.swing.JButton();
        btnFecharMenu = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnContaExcluir = new javax.swing.JButton();
        btnCancelarExcluir = new javax.swing.JButton();
        pswExcluirConta = new javax.swing.JPasswordField();
        lblDigitarSenha = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnEsconder = new javax.swing.JButton();
        lblBoxExcluir = new javax.swing.JLabel();
        cmbCategoriaEntrada = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        btnEntrada = new javax.swing.JButton();
        txtValorEntrada = new javax.swing.JTextField();
        lblEntradas = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCategoriaSaida = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSaida = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValorSaida = new javax.swing.JTextField();
        lblSaídas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setTitle("WELCOME BACK");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Saldo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 60, 30);

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(68, 128, 64));
        txtSaldo.setText("    R$ 1200.00");
        txtSaldo.setBorder(null);
        getContentPane().add(txtSaldo);
        txtSaldo.setBounds(90, 100, 140, 30);

        btnSair.setBackground(new java.awt.Color(255, 89, 49));
        btnSair.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 89, 49));
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setOpaque(true);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(740, 190, 80, 30);

        btnExcluirConta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnExcluirConta.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirConta.setText("Excluir conta");
        btnExcluirConta.setBorder(null);
        btnExcluirConta.setContentAreaFilled(false);
        btnExcluirConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirContaMouseExited(evt);
            }
        });
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirConta);
        btnExcluirConta.setBounds(710, 140, 140, 30);

        btnConsultar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(710, 60, 140, 30);

        lblBarraMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-barra-a.png"))); // NOI18N
        lblBarraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBarraMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblBarraMenuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblBarraMenuFocusLost(evt);
            }
        });
        lblBarraMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarraMenuMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBarraMenuMouseReleased(evt);
            }
        });
        getContentPane().add(lblBarraMenu);
        lblBarraMenu.setBounds(810, 20, 30, 30);

        btnAlterarDados.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAlterarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarDados.setText("Alterar dados");
        btnAlterarDados.setBorder(null);
        btnAlterarDados.setContentAreaFilled(false);
        btnAlterarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarDadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarDadosMouseExited(evt);
            }
        });
        btnAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarDados);
        btnAlterarDados.setBounds(710, 100, 140, 30);

        btnFecharMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-barra-a.png"))); // NOI18N
        btnFecharMenu.setBorder(null);
        btnFecharMenu.setContentAreaFilled(false);
        btnFecharMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFecharMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnFecharMenu);
        btnFecharMenu.setBounds(810, 20, 30, 30);

        lblMenu.setBackground(new java.awt.Color(179, 208, 102));
        lblMenu.setOpaque(true);
        getContentPane().add(lblMenu);
        lblMenu.setBounds(710, 10, 140, 240);

        lblWelcome.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(19, 96, 80));
        lblWelcome.setText("Welcome, Luccas! ;)");
        getContentPane().add(lblWelcome);
        lblWelcome.setBounds(30, 20, 260, 30);

        btnContaExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnContaExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnContaExcluir.setText("Excluir Conta");
        btnContaExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnContaExcluir);
        btnContaExcluir.setBounds(400, 180, 140, 30);

        btnCancelarExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelarExcluir.setText("Cancelar");
        btnCancelarExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarExcluir);
        btnCancelarExcluir.setBounds(280, 180, 100, 30);

        pswExcluirConta.setBackground(new java.awt.Color(204, 204, 204));
        pswExcluirConta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pswExcluirConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswExcluirContaKeyPressed(evt);
            }
        });
        getContentPane().add(pswExcluirConta);
        pswExcluirConta.setBounds(330, 90, 160, 30);

        lblDigitarSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDigitarSenha.setText("Digite sua senha:");
        getContentPane().add(lblDigitarSenha);
        lblDigitarSenha.setBounds(350, 20, 130, 50);

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (2) (1).png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(510, 90, 30, 30);

        btnEsconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho (1) (1).png"))); // NOI18N
        btnEsconder.setBorder(null);
        btnEsconder.setContentAreaFilled(false);
        btnEsconder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsconder);
        btnEsconder.setBounds(500, 120, 30, 30);

        lblBoxExcluir.setBackground(new java.awt.Color(255, 255, 255));
        lblBoxExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBoxExcluir.setOpaque(true);
        getContentPane().add(lblBoxExcluir);
        lblBoxExcluir.setBounds(250, 0, 330, 250);

        cmbCategoriaEntrada.setBackground(new java.awt.Color(179, 208, 102));
        cmbCategoriaEntrada.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmbCategoriaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        cmbCategoriaEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salario", "Freelance", "Outros" }));
        cmbCategoriaEntrada.setBorder(null);
        cmbCategoriaEntrada.setOpaque(true);
        cmbCategoriaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaEntradaActionPerformed(evt);
            }
        });
        cmbCategoriaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCategoriaEntradaKeyPressed(evt);
            }
        });
        getContentPane().add(cmbCategoriaEntrada);
        cmbCategoriaEntrada.setBounds(140, 250, 130, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 260, 90, 18);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de entrada:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 300, 130, 18);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 220, 50, 18);

        txtDataEntrada.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataEntradaKeyPressed(evt);
            }
        });
        getContentPane().add(txtDataEntrada);
        txtDataEntrada.setBounds(180, 290, 70, 30);

        btnEntrada.setBackground(new java.awt.Color(253, 235, 91));
        btnEntrada.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(68, 128, 64));
        btnEntrada.setText("Adicionar");
        btnEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrada);
        btnEntrada.setBounds(100, 370, 110, 30);

        txtValorEntrada.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtValorEntrada.setForeground(new java.awt.Color(255, 255, 255));
        txtValorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorEntradaKeyPressed(evt);
            }
        });
        getContentPane().add(txtValorEntrada);
        txtValorEntrada.setBounds(110, 210, 130, 30);

        lblEntradas.setBackground(new java.awt.Color(68, 128, 64));
        lblEntradas.setOpaque(true);
        getContentPane().add(lblEntradas);
        lblEntradas.setBounds(30, 190, 250, 280);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 250, 130, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Categoria:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 260, 90, 18);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data de entrada:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 300, 130, 18);

        txtDataSaida.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataSaidaKeyPressed(evt);
            }
        });
        getContentPane().add(txtDataSaida);
        txtDataSaida.setBounds(480, 290, 70, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel6.setText("Adicionar entradas");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 250, 20);

        cmbCategoriaSaida.setBackground(new java.awt.Color(255, 153, 153));
        cmbCategoriaSaida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmbCategoriaSaida.setForeground(new java.awt.Color(255, 255, 255));
        cmbCategoriaSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluguel", "Mercado", "Faculdade", "Escola", "Carro", "Outros" }));
        cmbCategoriaSaida.setBorder(null);
        cmbCategoriaSaida.setOpaque(true);
        cmbCategoriaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaSaidaActionPerformed(evt);
            }
        });
        cmbCategoriaSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCategoriaSaidaKeyPressed(evt);
            }
        });
        getContentPane().add(cmbCategoriaSaida);
        cmbCategoriaSaida.setBounds(440, 250, 130, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Valor:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 220, 50, 18);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data de entrada:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 300, 130, 18);

        btnSaida.setBackground(new java.awt.Color(253, 235, 91));
        btnSaida.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSaida.setForeground(new java.awt.Color(255, 89, 49));
        btnSaida.setText("Adicionar");
        btnSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaida);
        btnSaida.setBounds(400, 370, 110, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel5.setText("Adicionar saídas");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 160, 250, 20);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Categoria:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 260, 90, 18);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 220, 50, 18);

        txtValorSaida.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtValorSaida.setForeground(new java.awt.Color(255, 255, 255));
        txtValorSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorSaidaKeyPressed(evt);
            }
        });
        getContentPane().add(txtValorSaida);
        txtValorSaida.setBounds(410, 210, 130, 30);

        lblSaídas.setBackground(new java.awt.Color(255, 89, 49));
        lblSaídas.setOpaque(true);
        getContentPane().add(lblSaídas);
        lblSaídas.setBounds(330, 190, 250, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money-and-coin-b.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 220, 260, 260);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(180, 290, 100, 30);

        jButton3.setBackground(new java.awt.Color(253, 235, 91));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(68, 128, 64));
        jButton3.setText("Adicionar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 370, 110, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Valor:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 210, 50, 18);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(886, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBarraMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMenuMouseClicked
        btnFecharMenu.setVisible(true);
        lblBarraMenu.setVisible(false);
        showMenu();
    }//GEN-LAST:event_lblBarraMenuMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        btnFecharMenu.setVisible(false);
        lblBarraMenu.setVisible(true);
        hideMenu();
    }//GEN-LAST:event_formMouseClicked

    private void lblBarraMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMenuMouseReleased

    }//GEN-LAST:event_lblBarraMenuMouseReleased

    private void lblBarraMenuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblBarraMenuFocusLost

    }//GEN-LAST:event_lblBarraMenuFocusLost

    private void lblBarraMenuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblBarraMenuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarraMenuFocusGained

    private void btnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseEntered
        btnConsultar.setForeground(MY_YELLOW);
    }//GEN-LAST:event_btnConsultarMouseEntered

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        btnConsultar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnExcluirContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirContaMouseEntered
        btnExcluirConta.setForeground(MY_YELLOW);
    }//GEN-LAST:event_btnExcluirContaMouseEntered

    private void btnExcluirContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirContaMouseExited
        btnExcluirConta.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnExcluirContaMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setForeground(Color.WHITE);
        btnSair.setBackground(MY_RED);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setForeground(MY_RED);
        btnSair.setBackground(LIGHT_GREEN);
    }//GEN-LAST:event_btnSairMouseExited

    private void cmbCategoriaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaEntradaActionPerformed

    private void cmbCategoriaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaSaidaActionPerformed

    private void cmbCategoriaEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCategoriaEntradaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
            txtDataEntrada.requestFocus();
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtDataEntrada.requestFocus();
        }
    }//GEN-LAST:event_cmbCategoriaEntradaKeyPressed

    private void txtDataEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataEntradaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnEntrada.doClick();
        }
    }//GEN-LAST:event_txtDataEntradaKeyPressed

    private void cmbCategoriaSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCategoriaSaidaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
            txtDataSaida.requestFocus();
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtDataSaida.requestFocus();
        }
    }//GEN-LAST:event_cmbCategoriaSaidaKeyPressed

    private void txtDataSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataSaidaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnSaida.doClick();
        }


    }//GEN-LAST:event_txtDataSaidaKeyPressed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        boolean resposta;
        double result;
        MoneyControlDao dao;
        dao = new MoneyControlDao();
        
        if (txtValorEntrada.getText().equals("") || txtDataEntrada.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            txtValorEntrada.requestFocus();
            return;
        }
        
        String newValue;
        newValue = txtValorEntrada.getText().replaceAll(",", ".");
        double cV = Double.parseDouble(newValue);
        
        
        
        MoneyControl entrada;
        entrada = new MoneyControl(
                cV,
                cmbCategoriaEntrada.getSelectedItem().toString(),
                txtDataEntrada.getText()
        );
        
        resposta = dao.conectar();
        if (resposta) {
            result = dao.addEntrada(entrada, id);
            if (result == 1) {
                limparEntrada();
                txtValorEntrada.requestFocus();

                txtSaldo.setText(" R$ " + saldoAqui(id));
            } else {
                JOptionPane.showMessageDialog(null, "Erro de conexão. Tente novamente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro de conexão.");
        }
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        boolean resposta;
        double result;
        MoneyControlDao dao;
        dao = new MoneyControlDao();
        
        if (txtValorSaida.getText().equals("") || txtDataSaida.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            txtValorSaida.requestFocus();
            return;
        }
        
        String newValue;
        newValue = txtValorSaida.getText().replaceAll(",", ".");
        double cV = Double.parseDouble(newValue);

        MoneyControl entrada;
        entrada = new MoneyControl(
                cV,
                cmbCategoriaSaida.getSelectedItem().toString(),
                txtDataSaida.getText()
        );

        resposta = dao.conectar();
        if (resposta) {
            result = dao.addSaida(entrada, id);
            if (result == 1) {
                limparSaida();
                txtValorSaida.requestFocus();
                txtSaldo.setText(" R$ " + saldoAqui(id));
            } else {
                JOptionPane.showMessageDialog(null, "Erro de conexão. Tente novamente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro de conexão.");
        }
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
      
        this.dispose();
        LoginTela t;
        t = new LoginTela();
        t.setVisible(true);
        RelatorioMovimentacao r;
        r = new RelatorioMovimentacao();
        r.hide();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtValorEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEntradaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cmbCategoriaEntrada.requestFocus();
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
            cmbCategoriaEntrada.requestFocus();
        }
    }//GEN-LAST:event_txtValorEntradaKeyPressed

    private void txtValorSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorSaidaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cmbCategoriaSaida.requestFocus();
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
            cmbCategoriaEntrada.requestFocus();
        }
    }//GEN-LAST:event_txtValorSaidaKeyPressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        RelatorioMovimentacao rel;
        rel = new RelatorioMovimentacao();

        rel.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        showExcluirConta();
        naoClicavel();
        btnEsconder.setVisible(false);
        pswExcluirConta.requestFocus();
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnContaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaExcluirActionPerformed
        MoneyControlDao dao;
        dao = new MoneyControlDao();
        boolean excluiu;
        boolean conectou;

        conectou = dao.conectar();

        if (!pswExcluirConta.getText().equals(senha)) {
            JOptionPane.showMessageDialog(null, "Senha incorreta");
            pswExcluirConta.show(true);
            pswExcluirConta.requestFocus();
            return;
        }

        if (conectou) {
            excluiu = dao.excluirConta(id);
            if (excluiu) {
                JOptionPane.showMessageDialog(null, "Conta excluída com sucesso.");
                this.dispose();

                LoginTela t;
                t = new LoginTela();
                t.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Erro no sistema.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro na conexão");
        }
    }//GEN-LAST:event_btnContaExcluirActionPerformed

    private void pswExcluirContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswExcluirContaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnContaExcluir.doClick();
        }
    }//GEN-LAST:event_pswExcluirContaKeyPressed

    private void btnCancelarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarExcluirActionPerformed
        pswExcluirConta.setText("");
        hideExcluirConta();
        clicavel();
    }//GEN-LAST:event_btnCancelarExcluirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        pswExcluirConta.setEchoChar('\u0000');
        btnMostrar.setVisible(false);
        btnEsconder.setVisible(true);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEsconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderActionPerformed
        pswExcluirConta.setEchoChar('*');
        btnEsconder.setVisible(false);
        btnMostrar.setVisible(true);
    }//GEN-LAST:event_btnEsconderActionPerformed

    private void btnAlterarDadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarDadosMouseEntered
        btnAlterarDados.setForeground(MY_YELLOW);
    }//GEN-LAST:event_btnAlterarDadosMouseEntered

    private void btnAlterarDadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarDadosMouseExited
        btnAlterarDados.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAlterarDadosMouseExited

    private void btnAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarDadosActionPerformed
        TelaAlterarDados t = new TelaAlterarDados();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlterarDadosActionPerformed

    private void btnFecharMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMenuMouseClicked
        lblBarraMenu.setVisible(true);
        btnFecharMenu.setVisible(false);
        hideMenu();
    }//GEN-LAST:event_btnFecharMenuMouseClicked

    //MoneyControlDao dao = new MoneyControlDao();
    //double saldo = dao.saldo(id);
    private String saldoAqui(int id) {
        DecimalFormat df = new DecimalFormat("#,###.00");
        
        boolean resposta;
        MoneyControlDao dao = new MoneyControlDao();
        resposta = dao.conectar();
        double saldo = dao.saldo(id);

        if (saldo < 0) {
            txtSaldo.setForeground(MY_RED);
            return df.format(saldo);
        } else if (saldo > 0) {
            txtSaldo.setForeground(HARD_GREEN);
            return df.format(saldo);
        } else if (saldo == 0) {
            return "0,00";
        }
        return df.format(saldo);
    }

    private void naoClicavel() {
        txtValorEntrada.setEditable(false);
        cmbCategoriaEntrada.setEnabled(false);
        txtDataEntrada.setEnabled(false);
        txtValorSaida.setEditable(false);
        cmbCategoriaSaida.setEnabled(false);
        txtDataSaida.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnExcluirConta.setEnabled(false);
        btnSair.setEnabled(false);
        btnEntrada.setEnabled(false);
        btnSaida.setEnabled(false);
        btnAlterarDados.setEnabled(false);
    }

    private void clicavel() {
        txtValorEntrada.setEditable(true);
        cmbCategoriaEntrada.setEnabled(true);
        txtDataEntrada.setEnabled(true);
        txtValorSaida.setEditable(true);
        cmbCategoriaSaida.setEnabled(true);
        txtDataSaida.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnExcluirConta.setEnabled(true);
        btnSair.setEnabled(true);
        btnEntrada.setEnabled(true);
        btnSaida.setEnabled(true);
        btnAlterarDados.setEnabled(true);
    }

    private void hideExcluirConta() {
        lblBoxExcluir.setVisible(false);
        lblDigitarSenha.setVisible(false);
        pswExcluirConta.setVisible(false);
        btnCancelarExcluir.setVisible(false);
        btnContaExcluir.setVisible(false);
        btnMostrar.setVisible(false);
        btnEsconder.setVisible(false);
    }

    private void showExcluirConta() {
        lblBoxExcluir.setVisible(true);
        lblDigitarSenha.setVisible(true);
        pswExcluirConta.setVisible(true);
        btnCancelarExcluir.setVisible(true);
        btnContaExcluir.setVisible(true);
        btnMostrar.setVisible(true);
        btnEsconder.setVisible(true);
    }

    private void limparEntrada() {
        txtValorEntrada.setText("");
        cmbCategoriaEntrada.setSelectedItem("Salario");
        txtDataEntrada.setText("");
    }

    private void limparSaida() {
        txtValorSaida.setText("");
        cmbCategoriaSaida.setSelectedItem("Salario");
        txtDataSaida.setText("");
    }

    private void hideMenu() {
        lblMenu.setVisible(false);
        btnConsultar.setVisible(false);
        btnExcluirConta.setVisible(false);
        btnSair.setVisible(false);
        btnAlterarDados.setVisible(false);
    }

    private void showMenu() {
        lblMenu.setVisible(true);
        btnConsultar.setVisible(true);
        btnExcluirConta.setVisible(true);
        btnSair.setVisible(true);
        btnAlterarDados.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarDados;
    private javax.swing.JButton btnCancelarExcluir;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnContaExcluir;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnEsconder;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnFecharMenu;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbCategoriaEntrada;
    private javax.swing.JComboBox<String> cmbCategoriaSaida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblBarraMenu;
    private javax.swing.JLabel lblBoxExcluir;
    private javax.swing.JLabel lblDigitarSenha;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblSaídas;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPasswordField pswExcluirConta;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtDataSaida;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtValorEntrada;
    private javax.swing.JTextField txtValorSaida;
    // End of variables declaration//GEN-END:variables
}
